user:
  name:
    max_length: 50
  email:
    max_length: 100
  password:
    min_length: 8
    reset_time_expired: 2
  helper:
    gravatar:
      size: 80
  avatar_size: 50
micropost:
  content:
    max_length: 140
  max_picture_size: 5
feed:
  number_feed: 5
picture:
  resize_limit: 400
